name: Node.js Catpong

on:
  push:
    branches: [ "game" ]
  pull_request:
    branches: [ "game" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install
    - run: npm test
    - run: pm2 restart app-name
