on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:14
    steps:
    - run: npm install
    - run: npm --version
    - uses: actions/checkout@v4
    - run: npm install
    - run: node server start
